# -*- coding: utf-8 -*-
"""Assignment-08,1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YUMgs5FW5hA7d47swUjWUm9dcODi7LH-
"""

import streamlit as st
import pandas as pd
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
import pickle

st.write("""
#Subtraction of Two Number
""")
#Get Input

st.header('User Input Parameters')
def user_input_features():
  Number_01 = st.number_input("NUMBER_01",min_value=-500000000000000000,max_value=500000000000000000)
  Number_02 = st.number_input("NUMBER_02",min_value=-500000000000000000,max_value=500000000000000000)
 
  data = {'NUMBER_01': Number_01,
        'NUMBER_02': Number_02
         } 
  features = pd.DataFrame(data, index=[0])
  return features
        
df = user_input_features()

st.subheader('User Input parameters')
st.write(df.to_dict())

st.write(Number_01 - Number_02)



