# -*- coding: utf-8 -*-
"""Assignment-08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11xvfrRK8G45thuRmqmTrH9DTQD6fqjqo
"""

!pip install -q streamlit

from google.colab import drive
drive.mount('/content/drive')

!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip

!unzip ngrok-stable-linux-amd64.zip

! /content/ngrok authtoken 2CO1E8rsjyl0VxEAITkRLMW1tLB_cpCbtakqjoS9iyQyRC2o

get_ipython().system_raw('./ngrok http 8501 &')

!curl -s http://localhost:8501/api/tunnels | python3 -c \
    'import sys, json; print("Execute the next cell and the go to the following URL: " +json.load(sys.stdin)["tunnels"][0]["public_url"])'

!streamlit run /content/drive/MyDrive/Colab Notebooks/Assignment-08,1.ipynb

!pip3 freeze > requirements.txt

